/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.selectroshope;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author PROBOOK
 */
public class MAIN_FRAMEemp extends javax.swing.JFrame {
int USERID=0;
    /**
     * Creates new form MAIN_FRAME
     */
    public MAIN_FRAMEemp() {
        
        initComponents();
    }
    public int setUseid(int l){
        this.USERID=l;
        return 0;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        welcome_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        categories_panel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        category_id_txtf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        category_name_txtf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        category_description_txtf = new javax.swing.JTextField();
        deletecategory_button = new javax.swing.JButton();
        addcategory_button1 = new javax.swing.JButton();
        showcategorytable_button2 = new javax.swing.JButton();
        Cleancat_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryjTable = new javax.swing.JTable();
        customer_panel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        customer_id_txtf = new javax.swing.JTextField();
        customer_phone_txtf = new javax.swing.JTextField();
        customer_name_txtf = new javax.swing.JTextField();
        customer_address_txtf = new javax.swing.JTextField();
        addcustomer_button = new javax.swing.JButton();
        deletecustomer_button = new javax.swing.JButton();
        showcustomertable_button = new javax.swing.JButton();
        cleancustomer_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        product_panel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        product_price_txtf = new javax.swing.JTextField();
        product_manufacture_txtf = new javax.swing.JTextField();
        product_desc_txtf = new javax.swing.JTextField();
        product_name_txtf = new javax.swing.JTextField();
        product_id_txtf = new javax.swing.JTextField();
        product_category_id_txtf = new javax.swing.JTextField();
        product_quantity_txtf = new javax.swing.JTextField();
        addproduct_button = new javax.swing.JButton();
        deleteproduct_button = new javax.swing.JButton();
        showproducttable_button = new javax.swing.JButton();
        cleanpro_button = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        productsupp_txtf = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        supplier_price_txtf = new javax.swing.JTextField();
        order_panel = new javax.swing.JPanel();
        showordertable_button = new javax.swing.JButton();
        sendorder_button = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 650));

        jPanel1.setBackground(new java.awt.Color(18, 18, 66));
        jPanel1.setPreferredSize(new java.awt.Dimension(1319, 650));

        jPanel2.setBackground(new java.awt.Color(18, 18, 66));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PROBOOK\\Desktop\\jbdcproject\\project-management (1).png")); // NOI18N
        jLabel1.setText("SELECTRO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(18, 18, 66));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        welcome_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Jokerman", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 180, 31));
        jLabel2.setText("Welcome To Selectro Shope!");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PROBOOK\\Downloads\\chatbot.gif")); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout welcome_panelLayout = new javax.swing.GroupLayout(welcome_panel);
        welcome_panel.setLayout(welcome_panelLayout);
        welcome_panelLayout.setHorizontalGroup(
            welcome_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcome_panelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 626, Short.MAX_VALUE))
            .addGroup(welcome_panelLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        welcome_panelLayout.setVerticalGroup(
            welcome_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcome_panelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HOME", welcome_panel);

        categories_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setBackground(new java.awt.Color(18, 18, 66));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" Category ID");
        jLabel14.setOpaque(true);

        category_id_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));

        jLabel15.setBackground(new java.awt.Color(18, 18, 66));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("    Category Name");
        jLabel15.setOpaque(true);

        category_name_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));

        jLabel16.setBackground(new java.awt.Color(18, 18, 66));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" Category description");
        jLabel16.setOpaque(true);

        category_description_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));

        deletecategory_button.setText("Delete");
        deletecategory_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecategory_buttonActionPerformed(evt);
            }
        });

        addcategory_button1.setText("Add");
        addcategory_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcategory_button1ActionPerformed(evt);
            }
        });

        showcategorytable_button2.setText("Show Table");
        showcategorytable_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showcategorytable_button2ActionPerformed(evt);
            }
        });

        Cleancat_button.setText("Clean");
        Cleancat_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cleancat_buttonActionPerformed(evt);
            }
        });

        categoryjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category ID", "Category Name", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(categoryjTable);

        javax.swing.GroupLayout categories_panelLayout = new javax.swing.GroupLayout(categories_panel);
        categories_panel.setLayout(categories_panelLayout);
        categories_panelLayout.setHorizontalGroup(
            categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categories_panelLayout.createSequentialGroup()
                .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(categories_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(categories_panelLayout.createSequentialGroup()
                                .addComponent(addcategory_button1)
                                .addGap(151, 151, 151)
                                .addComponent(deletecategory_button)
                                .addGap(83, 83, 83)
                                .addComponent(Cleancat_button)
                                .addGap(57, 57, 57)
                                .addComponent(showcategorytable_button2))
                            .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(category_description_txtf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(categories_panelLayout.createSequentialGroup()
                                    .addComponent(category_id_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(98, 98, 98)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(category_name_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(categories_panelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        categories_panelLayout.setVerticalGroup(
            categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categories_panelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(category_id_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(category_name_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(category_description_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addcategory_button1)
                    .addComponent(deletecategory_button)
                    .addComponent(showcategorytable_button2)
                    .addComponent(Cleancat_button))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categories", categories_panel);

        customer_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setBackground(new java.awt.Color(18, 18, 66));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("   Customer ID");
        jLabel20.setOpaque(true);

        jLabel21.setBackground(new java.awt.Color(18, 18, 66));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("         Address");
        jLabel21.setOpaque(true);

        jLabel22.setBackground(new java.awt.Color(18, 18, 66));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("         Phone");
        jLabel22.setOpaque(true);

        jLabel23.setBackground(new java.awt.Color(18, 18, 66));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("  Customer Name");
        jLabel23.setOpaque(true);

        customer_id_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        customer_id_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_id_txtfActionPerformed(evt);
            }
        });

        customer_phone_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        customer_phone_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_phone_txtfActionPerformed(evt);
            }
        });

        customer_name_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        customer_name_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_name_txtfActionPerformed(evt);
            }
        });

        customer_address_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        customer_address_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_address_txtfActionPerformed(evt);
            }
        });

        addcustomer_button.setText("Add");
        addcustomer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcustomer_buttonActionPerformed(evt);
            }
        });

        deletecustomer_button.setText("Delete");
        deletecustomer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecustomer_buttonActionPerformed(evt);
            }
        });

        showcustomertable_button.setText("Show Table");
        showcustomertable_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showcustomertable_buttonActionPerformed(evt);
            }
        });

        cleancustomer_button.setText("Clean");
        cleancustomer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleancustomer_buttonActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Customer Name", "phone", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable3);

        javax.swing.GroupLayout customer_panelLayout = new javax.swing.GroupLayout(customer_panel);
        customer_panel.setLayout(customer_panelLayout);
        customer_panelLayout.setHorizontalGroup(
            customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_panelLayout.createSequentialGroup()
                .addGroup(customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customer_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customer_id_txtf, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(customer_phone_txtf))
                        .addGap(88, 88, 88)
                        .addGroup(customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customer_name_txtf, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(customer_address_txtf)))
                    .addGroup(customer_panelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(addcustomer_button)
                        .addGap(67, 67, 67)
                        .addComponent(deletecustomer_button)
                        .addGap(62, 62, 62)
                        .addComponent(cleancustomer_button)
                        .addGap(68, 68, 68)
                        .addComponent(showcustomertable_button))
                    .addGroup(customer_panelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        customer_panelLayout.setVerticalGroup(
            customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_id_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_name_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_phone_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_address_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addcustomer_button)
                    .addComponent(deletecustomer_button)
                    .addComponent(showcustomertable_button)
                    .addComponent(cleancustomer_button))
                .addGap(82, 82, 82)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", customer_panel);

        product_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setBackground(new java.awt.Color(18, 18, 66));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("   Product ID");
        jLabel24.setOpaque(true);

        jLabel25.setBackground(new java.awt.Color(18, 18, 66));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("   Product Name");
        jLabel25.setOpaque(true);

        jLabel26.setBackground(new java.awt.Color(18, 18, 66));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("    Description");
        jLabel26.setOpaque(true);

        jLabel28.setBackground(new java.awt.Color(18, 18, 66));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("   Manufacture");
        jLabel28.setOpaque(true);

        jLabel30.setBackground(new java.awt.Color(18, 18, 66));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("     Quantity");
        jLabel30.setOpaque(true);

        jLabel29.setBackground(new java.awt.Color(18, 18, 66));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("      Price");
        jLabel29.setOpaque(true);

        jLabel31.setBackground(new java.awt.Color(18, 18, 66));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("       Supplier");
        jLabel31.setOpaque(true);

        product_price_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        product_price_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_price_txtfActionPerformed(evt);
            }
        });

        product_manufacture_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        product_manufacture_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_manufacture_txtfActionPerformed(evt);
            }
        });

        product_desc_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        product_desc_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_desc_txtfActionPerformed(evt);
            }
        });

        product_name_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        product_name_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_name_txtfActionPerformed(evt);
            }
        });

        product_id_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        product_id_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_id_txtfActionPerformed(evt);
            }
        });

        product_category_id_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        product_category_id_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_category_id_txtfActionPerformed(evt);
            }
        });

        product_quantity_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        product_quantity_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_quantity_txtfActionPerformed(evt);
            }
        });

        addproduct_button.setText("Add");
        addproduct_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproduct_buttonActionPerformed(evt);
            }
        });

        deleteproduct_button.setText("Delete");
        deleteproduct_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteproduct_buttonActionPerformed(evt);
            }
        });

        showproducttable_button.setText("Show Table");
        showproducttable_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showproducttable_buttonActionPerformed(evt);
            }
        });

        cleanpro_button.setText("Clean");
        cleanpro_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanpro_buttonActionPerformed(evt);
            }
        });

        jLabel39.setBackground(new java.awt.Color(18, 18, 66));
        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("    Category ID");
        jLabel39.setOpaque(true);

        productsupp_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        productsupp_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsupp_txtfActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Description", "Manufacture", "Quantity", "Price", "Category ID", "Supplier Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jLabel32.setBackground(new java.awt.Color(18, 18, 66));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("   Spplier Price");
        jLabel32.setOpaque(true);

        supplier_price_txtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 18, 66)));
        supplier_price_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_price_txtfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout product_panelLayout = new javax.swing.GroupLayout(product_panel);
        product_panel.setLayout(product_panelLayout);
        product_panelLayout.setHorizontalGroup(
            product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_panelLayout.createSequentialGroup()
                .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(product_panelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(product_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(product_id_txtf))
                                .addGroup(product_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(product_price_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(product_panelLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(addproduct_button)
                                .addGap(43, 43, 43)
                                .addComponent(deleteproduct_button)
                                .addGap(41, 41, 41)
                                .addComponent(cleanpro_button)
                                .addGap(65, 65, 65)
                                .addComponent(showproducttable_button))
                            .addGroup(product_panelLayout.createSequentialGroup()
                                .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(product_desc_txtf, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(product_panelLayout.createSequentialGroup()
                                            .addComponent(supplier_price_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(344, 344, 344)))
                                    .addGroup(product_panelLayout.createSequentialGroup()
                                        .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(product_panelLayout.createSequentialGroup()
                                                .addComponent(product_manufacture_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(358, 358, 358)))
                                        .addGap(18, 18, 18)
                                        .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(product_quantity_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(product_name_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(product_category_id_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(productsupp_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39))))))
                    .addGroup(product_panelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        product_panelLayout.setVerticalGroup(
            product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(product_id_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(product_name_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(product_price_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(product_quantity_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(product_panelLayout.createSequentialGroup()
                        .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(product_category_id_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productsupp_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(product_panelLayout.createSequentialGroup()
                        .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(product_manufacture_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplier_price_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(product_desc_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addproduct_button)
                    .addComponent(deleteproduct_button)
                    .addComponent(cleanpro_button)
                    .addComponent(showproducttable_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jTabbedPane1.addTab("Product", product_panel);

        order_panel.setBackground(new java.awt.Color(255, 255, 255));

        showordertable_button.setText("Previous order");
        showordertable_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showordertable_buttonActionPerformed(evt);
            }
        });

        sendorder_button.setText("Send Order");
        sendorder_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendorder_buttonActionPerformed(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Employee ID", "Order Time", "Order Date", "Payment Methode", "Customer ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout order_panelLayout = new javax.swing.GroupLayout(order_panel);
        order_panel.setLayout(order_panelLayout);
        order_panelLayout.setHorizontalGroup(
            order_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(order_panelLayout.createSequentialGroup()
                .addGroup(order_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(order_panelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(order_panelLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(showordertable_button)
                        .addGap(171, 171, 171)
                        .addComponent(sendorder_button)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        order_panelLayout.setVerticalGroup(
            order_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(order_panelLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(order_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showordertable_button)
                    .addComponent(sendorder_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Order", order_panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deletecategory_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecategory_buttonActionPerformed
        // TODO add your handling code here:
          try {
           
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
            String qry1="delete from  selectro.product  where category_id="+Integer.parseInt(this.category_id_txtf.getText());
            String qry = "delete from  selectro.category  where category_id="+Integer.parseInt(this.category_id_txtf.getText());
            Statement stmt = con.createStatement();
             stmt.executeUpdate(qry1);
            stmt.executeUpdate(qry);
            
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(MAIN_FRAMEemp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletecategory_buttonActionPerformed

    private void addcategory_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcategory_button1ActionPerformed
          try {
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
            String qry="insert into selectro.category values("+this.category_id_txtf.getText()+",'"+this.category_name_txtf.getText()+"','"+this.category_description_txtf.getText()+"')";
            Statement stmt=con.createStatement();
            stmt.executeUpdate(qry);
            con.close();
            
           } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null,ex.toString());
        
        
    }                    
    }//GEN-LAST:event_addcategory_button1ActionPerformed

    private void showcategorytable_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showcategorytable_button2ActionPerformed
        // TODO add your handling code here:
        
          try {
            // TODO add your handling code here:
            
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
            String qry = "select * from  selectro.category ";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(qry);
         
            
            DefaultTableModel mod=(DefaultTableModel)categoryjTable.getModel();
            mod.setRowCount(0);
            while (rs.next()){
              int catid=rs.getInt(1);
              String catName=rs.getString(2);
              String catdesc=rs.getString(3);
             
              mod=(DefaultTableModel)categoryjTable.getModel();
                   mod.addRow(new Object[]{catid,catName,catdesc});
   
           
            }
        } catch (SQLException ex) {        
            JOptionPane.showConfirmDialog(null, ex.toString());
        }
         
        
        
        
    }//GEN-LAST:event_showcategorytable_button2ActionPerformed

    private void customer_id_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_id_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_id_txtfActionPerformed

    private void customer_phone_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_phone_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_phone_txtfActionPerformed

    private void customer_name_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_name_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_name_txtfActionPerformed

    private void customer_address_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_address_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_address_txtfActionPerformed

    private void addcustomer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcustomer_buttonActionPerformed
          try {
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
            String qry="insert into selectro.customer values("+this.customer_id_txtf.getText()+",'"+this.customer_name_txtf.getText()+"','"+this.customer_phone_txtf.getText()+"','"+this.customer_address_txtf.getText()+"')";
            Statement stmt=con.createStatement();
            stmt.executeUpdate(qry);
            con.close();
            
           } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null,ex.toString());
        
        
    }                   
    }//GEN-LAST:event_addcustomer_buttonActionPerformed

    private void deletecustomer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecustomer_buttonActionPerformed
        // TODO add your handling code here:
            try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
            String qry = "delete from  selectro.customer where customer_id="+this.customer_id_txtf.getText();
            Statement stmt = con.createStatement();
            stmt.executeUpdate(qry);
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(MAIN_FRAMEemp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletecustomer_buttonActionPerformed

    private void showcustomertable_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showcustomertable_buttonActionPerformed
        // TODO add your handling code here:
        
          try {
            // TODO add your handling code here:
            
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
            String qry = "select * from  selectro.customer ";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(qry);
         
            
            DefaultTableModel mod=(DefaultTableModel)jTable3.getModel();
            mod.setRowCount(0);
              
         while (rs.next()){
              int customerid=rs.getInt(1);
              String customerName=rs.getString(2);
              String customerphone=rs.getString(3);
              String customeraddress=rs.getString(4);
             
              mod=(DefaultTableModel)jTable3.getModel();
                   mod.addRow(new Object[]{customerid,customerName,customerphone,customeraddress});
   
           
            }
        } catch (SQLException ex) {        
            JOptionPane.showConfirmDialog(null, ex.toString());
        }
        
        
        
        
        
        
        
        
        
     
    }//GEN-LAST:event_showcustomertable_buttonActionPerformed

    private void product_price_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_price_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_price_txtfActionPerformed

    private void product_manufacture_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_manufacture_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_manufacture_txtfActionPerformed

    private void product_desc_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_desc_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_desc_txtfActionPerformed

    private void product_name_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_name_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_name_txtfActionPerformed

    private void product_id_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_id_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_id_txtfActionPerformed

    private void product_category_id_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_category_id_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_category_id_txtfActionPerformed

    private void product_quantity_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_quantity_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_quantity_txtfActionPerformed

    private void addproduct_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproduct_buttonActionPerformed
        // TODO add your handling code here:
        try {
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
            String qry="insert into selectro.product values("+this.product_id_txtf.getText()+",'"+this.product_name_txtf.getText()+"','"+this.product_desc_txtf.getText()+"','"+this.product_manufacture_txtf.getText()+"',"+this.product_quantity_txtf.getText()+","+this.product_price_txtf.getText()+","+this.product_category_id_txtf.getText()+","+this.supplier_price_txtf.getText()+")";
            
          String st=this.productsupp_txtf.getText();
            String[] array = st.split(",");
            
            Statement stmt=con.createStatement();
            stmt.executeUpdate(qry);
            
            for (String part : array){
                String qry1="insert into selectro.product_supplier values("+Integer.parseInt(this.product_id_txtf.getText())+","+Integer.parseInt(part)+")";
           stmt.executeUpdate(qry1);
           }
            con.close();
            
           } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null,ex.toString());
           }
         
    }//GEN-LAST:event_addproduct_buttonActionPerformed

    private void deleteproduct_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteproduct_buttonActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
            String qry1="delete from  selectro.product_supplier  where product_id="+Integer.parseInt(this.product_id_txtf.getText());
            String qry = "delete from  selectro.product where product_id="+this.product_id_txtf.getText();
            Statement stmt = con.createStatement();
            stmt.executeUpdate(qry1);
            stmt.executeUpdate(qry);
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(MAIN_FRAMEemp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteproduct_buttonActionPerformed

    private void showproducttable_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showproducttable_buttonActionPerformed
        // TODO add your handling code here:
        
         
         
          try {
            // TODO add your handling code here:
            
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
             String qry = "select * from  selectro.product ";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(qry);
         
            
            DefaultTableModel mod=(DefaultTableModel)jTable4.getModel();
            mod.setRowCount(0);
              
           while (rs.next()){
              int proid=rs.getInt(1);
              String proName=rs.getString(2);
              String proDescription=rs.getString(3);
              String proManufacture=rs.getString(4);
              int proQuantity=rs.getInt(5);
              String proPrice=rs.getString(6);
              int pro_catid=rs.getInt(7);
              String sppprice= rs.getString(8);
             
              mod=(DefaultTableModel)jTable4.getModel();
                   mod.addRow(new Object[]{proid,proName,proDescription,proManufacture,proQuantity,proPrice,pro_catid,sppprice});
   
           
            }
        } catch (SQLException ex) {        
            JOptionPane.showConfirmDialog(null, ex.toString());
        }
         
         
   
         
    }//GEN-LAST:event_showproducttable_buttonActionPerformed

    private void Cleancat_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cleancat_buttonActionPerformed
        // TODO add your handling code here:
        this.category_id_txtf.setText("");
        this.category_name_txtf.setText("");
        this.category_description_txtf.setText("");
        
        
    }//GEN-LAST:event_Cleancat_buttonActionPerformed

    private void cleancustomer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleancustomer_buttonActionPerformed
        // TODO add your handling code here:
          this.customer_id_txtf.setText("");
        this.customer_name_txtf.setText("");
        this.customer_phone_txtf.setText("");
        this.customer_address_txtf.setText("");
    }//GEN-LAST:event_cleancustomer_buttonActionPerformed

    private void cleanpro_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanpro_buttonActionPerformed
        // TODO add your handling code here:
         this.product_id_txtf.setText("");
        this.product_name_txtf.setText("");
        this.product_manufacture_txtf.setText("");
        this.product_desc_txtf.setText("");
         this.product_price_txtf.setText("");
        this.product_quantity_txtf.setText("");
        this.product_category_id_txtf.setText("");
       this.supplier_price_txtf.setText("");
       this.productsupp_txtf.setText("");
    }//GEN-LAST:event_cleanpro_buttonActionPerformed

    private void showordertable_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showordertable_buttonActionPerformed
         try {
            // TODO add your handling code here:
            
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
             String qry = "select * from  selectro.order where selectro.order.employee_id="+this.USERID;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(qry);
         
            
            DefaultTableModel mod=(DefaultTableModel)jTable5.getModel();
            mod.setRowCount(0);
              
           while (rs.next()){
              int ordid=rs.getInt(1);
                int empid=rs.getInt(2);
            
              String ordtime=rs.getString(3);
              String orderdate=rs.getString(4);
              String paymethod=rs.getString(5);
              int custid=rs.getInt(6);
              
             
              mod=(DefaultTableModel)jTable5.getModel();
                   mod.addRow(new Object[]{ordid,empid,ordtime,orderdate,paymethod,custid});
   
           
            }
        } catch (SQLException ex) {        
            JOptionPane.showConfirmDialog(null, ex.toString());
        }
         

        
    }//GEN-LAST:event_showordertable_buttonActionPerformed

    private void productsupp_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsupp_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productsupp_txtfActionPerformed

    private void sendorder_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendorder_buttonActionPerformed
        // TODO add your handling code here:
        orders a=new orders();
        a.setUseid(this.USERID);
       try {
           
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
            String qry = "select product_name from  selectro.product ";
            
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(qry);
          
       while(rs.next()){
       String pro=rs.getString(1);
       a.ordersbox_button.addItem(pro);
      
       }
       
       String qry1="select customer_id from  selectro.customer";
     rs = stmt.executeQuery(qry1);
       
       while(rs.next()){
       String customerid=rs.getString(1);
       a.CUSTOMERIDjComboBox2.addItem(customerid);
      
       }
       
 
           con.close();
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, ex.toString());
        }
         a.setVisible(true);
         
        
     
         
    }//GEN-LAST:event_sendorder_buttonActionPerformed

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
 
     
    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
       
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void supplier_price_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_price_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplier_price_txtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_FRAMEemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_FRAMEemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_FRAMEemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_FRAMEemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MAIN_FRAMEemp().setVisible(true);
                
              
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cleancat_button;
    private javax.swing.JButton addcategory_button1;
    private javax.swing.JButton addcustomer_button;
    private javax.swing.JButton addproduct_button;
    private javax.swing.JPanel categories_panel;
    private javax.swing.JTextField category_description_txtf;
    private javax.swing.JTextField category_id_txtf;
    private javax.swing.JTextField category_name_txtf;
    private javax.swing.JTable categoryjTable;
    private javax.swing.JButton cleancustomer_button;
    private javax.swing.JButton cleanpro_button;
    private javax.swing.JTextField customer_address_txtf;
    private javax.swing.JTextField customer_id_txtf;
    private javax.swing.JTextField customer_name_txtf;
    private javax.swing.JPanel customer_panel;
    private javax.swing.JTextField customer_phone_txtf;
    private javax.swing.JButton deletecategory_button;
    private javax.swing.JButton deletecustomer_button;
    private javax.swing.JButton deleteproduct_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JPanel order_panel;
    private javax.swing.JTextField product_category_id_txtf;
    private javax.swing.JTextField product_desc_txtf;
    private javax.swing.JTextField product_id_txtf;
    private javax.swing.JTextField product_manufacture_txtf;
    private javax.swing.JTextField product_name_txtf;
    private javax.swing.JPanel product_panel;
    private javax.swing.JTextField product_price_txtf;
    private javax.swing.JTextField product_quantity_txtf;
    private javax.swing.JTextField productsupp_txtf;
    private javax.swing.JButton sendorder_button;
    private javax.swing.JButton showcategorytable_button2;
    private javax.swing.JButton showcustomertable_button;
    private javax.swing.JButton showordertable_button;
    private javax.swing.JButton showproducttable_button;
    private javax.swing.JTextField supplier_price_txtf;
    private javax.swing.JPanel welcome_panel;
    // End of variables declaration//GEN-END:variables
}
