/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.selectroshope;

import static com.lowagie.text.pdf.PdfFileSpecification.url;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author PROBOOK
 */
public class orders extends javax.swing.JFrame {
int ouser=0;
    /**
     * Creates new form orders
     */
    public orders() {
        initComponents();
    }
 public int setUseid(int k){
        this.ouser=k;
        return 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ordersbox_button = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        theorderquantity_txtf = new javax.swing.JTextField();
        Addthispro_button = new javax.swing.JButton();
        deletethispro_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        totalprice_txtf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CUSTOMERIDjComboBox2 = new javax.swing.JComboBox<>();
        confirm_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setText("Quantity");

        Addthispro_button.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        Addthispro_button.setText("Add");
        Addthispro_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addthispro_buttonActionPerformed(evt);
            }
        });

        deletethispro_button.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        deletethispro_button.setText("Delete");
        deletethispro_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletethispro_buttonActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "On item price", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa", "MasterCard" }));

        totalprice_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalprice_txtfActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setText("Total Price");

        confirm_button.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        confirm_button.setText("Confirm");
        confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_buttonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jButton1.setText("Cancle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PROBOOK\\Desktop\\jbdcproject\\credit-card.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\PROBOOK\\Desktop\\jbdcproject\\friend.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(30, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(167, 167, 167)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(CUSTOMERIDjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(deletethispro_button, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(totalprice_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(confirm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(ordersbox_button, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Addthispro_button, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(theorderquantity_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(49, 49, 49)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordersbox_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(theorderquantity_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Addthispro_button)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(totalprice_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(confirm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deletethispro_button)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(CUSTOMERIDjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_buttonActionPerformed
        int OrderID =1 ;

        try {
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
            Instant instant = Instant.now();
            LocalTime localTime = LocalTime.now();
            LocalDate zonedDateTime = LocalDate.now();

            String qry1="insert into selectro.order  (employee_id,order_time,order_date,payment_method,customer_id) values("+this.ouser+",'"+localTime+"','"+zonedDateTime+"','"+this.jComboBox1.getSelectedItem()+"',"+Integer.parseInt(this.CUSTOMERIDjComboBox2.getSelectedItem().toString())+")";
            Statement stmt=con.createStatement();
            stmt.executeUpdate(qry1);

            con.close();
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
        //My new Code
        try {
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
            String qry = "select * from  selectro.order order by order_id DESC LIMIT 1";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(qry);
            while (rs.next()){
                OrderID=rs.getInt(1);
            }
            con.close();
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
        for (int i =0; i<this.jTable2.getRowCount();i++){
            int productID =1 ;
            int WnatedQty=0;
            int availabel=0;
            try {
                // TODO add your handling code here:
                DriverManager.registerDriver(new org.postgresql.Driver() );
                String connInfo="jdbc:postgresql://localhost:5432/postgres";
                Connection con=DriverManager.getConnection(connInfo,"dima","123456");
                String qry = "select * from  selectro.product  where product_name='"+this.jTable2.getValueAt(i, 0).toString()+"'";
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(qry);
                while (rs.next()){
                    productID= rs.getInt(1);
                    availabel= rs.getInt(5);
                }

                // here we want to add the contents of the product int the oder_produuct tabel

                try {

                    String qry4="insert into selectro.product_order values("+productID+","+OrderID+","+Integer.parseInt(this.jTable2.getValueAt(i, 2).toString())+","+this.jTable2.getValueAt(i, 1).toString()+","+this.jTable2.getValueAt(i, 3).toString()+")";
                    Statement stmt1=con.createStatement();
                    stmt.executeUpdate(qry4);
                    con.close();

                } catch (Exception ex) {
                    JOptionPane.showConfirmDialog(null,ex.toString());
                }
            } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(null, ex.toString());
            }
            // HERE THE ODERED-AVAILABL
            try {
                // TODO add your handling code here:
                DriverManager.registerDriver(new org.postgresql.Driver() );
                String connInfo="jdbc:postgresql://localhost:5432/postgres";
                Connection con=DriverManager.getConnection(connInfo,"dima","123456");
                int subtraction=availabel-Integer.parseInt(this.jTable2.getValueAt(i, 2).toString());
                String qry ;
                if (subtraction==0){
                    qry = "Update selectro.product   set  quantity ="+0+"  where product_id="+productID ;

                }
                else{
                    qry = "Update selectro.product   set  quantity ="+subtraction+"  where product_id="+productID ;
                }
                Statement stmt = con.createStatement();
                stmt.executeUpdate(qry);
                con.close();
            } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(null,ex.toString());
            }

            this.setVisible(false);
        }

 try {
            // TODO add your handling code here:
            Connection con;
            InputStream input;
            JasperDesign jd;
            JasperReport jr;
            JasperPrint jp;
            OutputStream output;
            DriverManager. deregisterDriver (new org.postgresql. Driver ());
            con=DriverManager.getConnection ( "jdbc:postgresql://localhost:5432/postgres","dima","123456");
            input=new FileInputStream (new File ("bills.jrxml")) ;
            jd=JRXmlLoader.load(input);
            jr=JasperCompileManager.compileReport(jd);
            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("orderid",OrderID );
            jp=JasperFillManager.fillReport(jr,parameters,con);
            String bath="Bills/BillNum"+OrderID+".pdf";
            output=new FileOutputStream(new File(bath));
            
            
            
            JasperExportManager.exportReportToPdfStream(jp, output);
            
            
            JFrame frame=new JFrame("BILL");
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);
            output.close();
            input.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(MAIN_FRAME.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MAIN_FRAME.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(MAIN_FRAME.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MAIN_FRAME.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        }

        private void TotalPriceLabelActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:

    }//GEN-LAST:event_confirm_buttonActionPerformed

    private void totalprice_txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalprice_txtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalprice_txtfActionPerformed

    private void deletethispro_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletethispro_buttonActionPerformed
        // TODO add your handling code here:

        DefaultTableModel DFT= (DefaultTableModel ) this.jTable2.getModel();
        if (this.jTable2.getSelectedRowCount()==1){

            int rowindx= this.jTable2.getSelectedRow();
            Object todelete = new Object();
            todelete=this.jTable2.getValueAt(rowindx, 3);
            float z= (float)todelete;
            float sub= Float.parseFloat(this.totalprice_txtf.getText())-z;
            this.totalprice_txtf.setText(Float.toString(sub));
            DFT.removeRow(this.jTable2.getSelectedRow());
        }
        else{
            JOptionPane.showConfirmDialog(null, "You Can Delete One ow At a Time ");

        }
    }//GEN-LAST:event_deletethispro_buttonActionPerformed

    private void Addthispro_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addthispro_buttonActionPerformed

        try {
            // TODO add your handling code here:
            int wantedqty=Integer.parseInt(this.theorderquantity_txtf.getText());
            DriverManager.registerDriver(new org.postgresql.Driver() );
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"dima","123456");
            String qry = "select * from  selectro.product  where product_name='"+this.ordersbox_button.getSelectedItem()+"'";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(qry);
            while (rs.next()){
                int availabelqty = rs.getInt(5);
                if (wantedqty<=availabelqty){
                    //the order is valied

                    String temp=rs.getString(6);
                    temp= temp.substring(0);
                    float groupproductsprice=wantedqty*Float.parseFloat(temp);
                    DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
                    model.addRow(new Object[]{this.ordersbox_button.getSelectedItem(),temp,wantedqty,groupproductsprice});
                    float sum=0;
                    for(int i=0;i<jTable2.getRowCount();i++){
                        sum=sum+Float.parseFloat(jTable2.getValueAt(i,3).toString());

                    }

                    this.totalprice_txtf.setText(Float.toString(sum));

                }
                else {
                    JOptionPane.showConfirmDialog(null, "Sorry this Quantity is NOT a vailabel the Availabel is " + availabelqty);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, ex.toString());
        }

    }//GEN-LAST:event_Addthispro_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addthispro_button;
    public javax.swing.JComboBox<String> CUSTOMERIDjComboBox2;
    private javax.swing.JButton confirm_button;
    private javax.swing.JButton deletethispro_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    public javax.swing.JComboBox<String> ordersbox_button;
    private javax.swing.JTextField theorderquantity_txtf;
    private javax.swing.JTextField totalprice_txtf;
    // End of variables declaration//GEN-END:variables
}
